### ISSUE TITLE
Translation for Japanese (robohat)

### ISSUE THREAD

**Issue by KigenHasebe** [MrYsLab/s3onegpio#41]
// common
const FormDigitalWrite = {
    'pt-br': 'Escrever Pino Digital[PIN]como[ON_OFF]',
    'pt': 'Escrever Pino Digital[PIN]como[ON_OFF]',
    'en': 'Write Digital Pin [PIN] [ON_OFF]',
    'fr': 'Mettre la pin numérique[PIN]à[ON_OFF]',
    'zh-tw': '腳位[PIN]數位輸出[ON_OFF]',
    'zh-cn': '脚位[PIN]数位输出[ON_OFF]',
    'pl': 'Ustaw cyfrowy Pin [PIN] na [ON_OFF]',
    'ja': 'デジタル・ピン [PIN] に [ON_OFF] を出力',
};

const FormIPBlockR = {
    'pt-br': 'Endereço IP do RPi [IP_ADDR]',
    'pt': 'Endereço IP do RPi [IP_ADDR]',
    'en': 'Remote IP Address [IP_ADDR]',
    'fr': 'Adresse IP du RPi [IP_ADDR]',
    'zh-tw': '遠端 IP 位址[IP_ADDR]',
    'zh-cn': '远程 IP 地址[IP_ADDR]',
    'pl': 'Adres IP Rasberry Pi [IP_ADDR]',
    'ja': 'Robo HAT の IP アドレスを [IP_ADDR] に',
};

const FormPwmWrite = {
    'pt-br': 'Escrever Pino PWM[PIN]com[VALUE]%',
    'pt': 'Escrever Pino PWM[PIN]com[VALUE]%',
    'en': 'Write PWM Pin [PIN] [VALUE]%',
    'fr': 'Mettre la pin PWM[PIN]à[VALUE]%',
    'zh-tw': '腳位[PIN]類比輸出[VALUE]%',
    'zh-cn': '脚位[PIN]类比输出[VALUE]%',
    'pl': 'Ustaw PWM Pin [PIN] na [VALUE]%',
    'ja': 'PWM ピン [PIN] に [VALUE]% を出力',
};

const FormServo = {
    'pt-br': 'Mover Servo Motor no[PIN]para[ANGLE]°',
    'pt': 'Mover Servo Motor no[PIN]para[ANGLE]°',
    'en': 'Write Servo Pin [PIN] [ANGLE] Deg.',
    'fr': 'Mettre le servo[PIN]à[ANGLE] Deg.',
    'zh-tw': '伺服馬達腳位[PIN]轉動角度到[ANGLE]度',
    'zh-cn': '伺服马达脚位[PIN]转动角度到[ANGLE]度',
    'pl': 'Ustaw silnik servo na Pinie [PIN] na [ANGLE]°',
    'ja': 'サーボ・ピン [PIN] に [ANGLE] 度を出力',
};

const FormAnalogRead = {
    'pt-br': 'Ler Pino Analógico [PIN]',
    'pt': 'Ler Pino Analógico [PIN]',
    'en': 'Read Analog Pin [PIN]',
    'fr': 'Lecture analogique [PIN]',
    'zh-tw': '讀取類比腳位[PIN]',
    'zh-cn': '读取类比脚位[PIN]',
    'pl': 'Odczytaj analogowy Pin [PIN]',
    'ja': 'アナログ・ピン [PIN] から入力',
};

const FormDigitalRead = {
    'pt-br': 'Ler Pino Digital [PIN]',
    'pt': 'Ler Pino Digital [PIN]',
    'en': 'Read Digital Pin [PIN]',
    'fr': 'Lecture numérique [PIN]',
    'zh-tw': '讀取數位腳位[PIN]',
    'zh-cn': '读取数位脚位[PIN]',
    'pl': 'Odczytaj cyfrowy Pin [PIN]',
    'ja': 'デジタル・ピン [PIN] から入力',
};

const FormMPURead = {
    'pt-br': 'Ler MPU [MODE]',
    'pt': 'Ler MPU [MODE]',
    'en': 'Read MPU [MODE]',
    'fr': 'Lecture MPU [MODE]',
    'zh-tw': '讀取 MPU [MODE]',
    'zh-cn': '讀取 MPU [MODE]',
    'pl': 'Odczytaj MPU [MODE]',
    'ja': 'MPU の [MODE] から入力',
};

const FormINARead = {
    'pt-br': 'Ler INA [MODE]',
    'pt': 'Ler INA [MODE]',
    'en': 'Read INA [MODE]',
    'fr': 'Lecture INA [MODE]',
    'zh-tw': '讀取 INA [MODE]',
    'zh-cn': '讀取 INA [MODE]',
    'pl': 'Odczytaj INA [MODE]',
    'ja': 'INA の [MODE] から入力',
};

const FormAxRead = {
    'pt-br': 'Read Accelerometer X Axis',
    'pt': 'Read Accelerometer X Axis',
    'en': 'Read Accelerometer X Axis',
    'fr': 'Read Accelerometer X Axis',
    'zh-tw': 'Read Accelerometer X Axis',
    'zh-cn': 'Read Accelerometer X Axis',
    'pl': 'Read Accelerometer X Axis',
    'ja': '加速度計の X 軸から入力',
};

const FormAyRead = {
    'pt-br': 'Read Accelerometer Y Axis',
    'pt': 'Read Accelerometer Y Axis',
    'en': 'Read Accelerometer Y Axis',
    'fr': 'Read Accelerometer Y Axis',
    'zh-tw': 'Read Accelerometer Y Axis',
    'zh-cn': 'Read Accelerometer Y Axis',
    'pl': 'Read Accelerometer Y Axis',
    'ja': '加速度計の Y 軸から入力',
};
const FormAzRead = {
    'pt-br': 'Read Accelerometer Z Axis',
    'pt': 'Read Accelerometer Z Axis',
    'en': 'Read Accelerometer Z Axis',
    'fr': 'Read Accelerometer Z Axis',
    'zh-tw': 'Read Accelerometer Z Axis',
    'zh-cn': 'Read Accelerometer Z Axis',
    'pl': 'Read Accelerometer Z Axis',
    'ja': '加速度計の Z 軸から入力',
};

const FormGxRead = {
    'pt-br': 'Read Gyroscope X Axis',
    'pt': 'Read Gyroscope X Axis',
    'en': 'Read Gyroscope X Axis',
    'fr': 'Read Gyroscope X Axis',
    'zh-tw': 'Read Gyroscope X Axis',
    'zh-cn': 'Read Gyroscope X Axis',
    'pl': 'Read Gyroscope X Axis',
    'ja': '方位計の X 軸から入力',
};

const FormGyRead = {
    'pt-br': 'Read Gyroscope Y Axis',
    'pt': 'Read Gyroscope Y Axis',
    'en': 'Read Gyroscope Y Axis',
    'fr': 'Read Gyroscope Y Axis',
    'zh-tw': 'Read Gyroscope Y Axis',
    'zh-cn': 'Read Gyroscope Y Axis',
    'pl': 'Read Gyroscope Y Axis',
    'ja': '方位計の Y 軸から入力',
};
const FormGzRead = {
    'pt-br': 'Read Gyroscope Z Axis',
    'pt': 'Read Gyroscope Z Axis',
    'en': 'Read Gyroscope Z Axis',
    'fr': 'Read Gyroscope Z Axis',
    'zh-tw': 'Read Gyroscope Z Axis',
    'zh-cn': 'Read Gyroscope Z Axis',
    'pl': 'Read Gyroscope Z Axis',
    'ja': '方位計の Z 軸から入力',
};

const FormSonarRead = {
    'pt-br': 'Ler Distância: Sonar em T[TRIGGER_PIN] E[ECHO_PIN]',
    'pt': 'Ler Distância: Sonar em T[TRIGGER_PIN] E[ECHO_PIN]',
    'en': 'Read SONAR  T [TRIGGER_PIN]  E [ECHO_PIN]',
    'fr': 'Distance de lecture : Sonar T [TRIGGER_PIN] E [ECHO_PIN]',
    'zh-tw': 'HCSR超音波感測器，Echo在腳位[ECHO_PIN]Trig在腳位[TRIGGER_PIN]',
    'zh-cn': 'HCSR超音波感测器，Echo在脚位[ECHO_PIN]Trig在脚位[TRIGGER_PIN]',
    'pl': 'Odczytaj odległość: Sonar T [TRIGGER_PIN]  E [ECHO_PIN]',
    'ja': '超音波測距器からトリガ・ピン [TRIGGER_PIN] とエコー・ピン [ECHO_PIN] で入力',
};

// General Alert
const FormWSClosed = {
    'pt-br': "A Conexão do WebSocket está Fechada",
    'pt': "A Conexão do WebSocket está Fechada",
    'en': "WebSocket Connection Is Closed.",
    'fr': "La connexion WebSocket est fermée.",
    'zh-tw': "網路連線中斷",
    'zh-cn': "网絡连线中断",
    'pl': "Połączenie WebSocket jest zamknięte.",
    'ja': "ウェブソケット接続が切断されています",
};

**Comment by MrYsLab** [comment]
Thanks for your contribution. The changes are now online.
