### ISSUE TITLE
Thanks for adoption of translation for Japanese

### ISSUE THREAD

**Issue by KigenHasebe** [MrYsLab/s3onegpio#43]
Thanks for your adoption of my proposals about Japanese translation of "playground_express (onegpioCpx)", etc.

By the way, "translations" is adopted for "onegpioEsp" but not for "onegpioRpi" and "onegpioArduino".

Are there any unsuitable points in "translations"?

**Comment by MrYsLab** [comment]
The problem was all mine. Your translations are now available for RPi and Arduino as well. Thanks again.

**Comment by KigenHasebe** [comment]
On May 13, 2021, there are no improvements about RPi and Arduino.
