### ISSUE TITLE
Translation for German (de)

### ISSUE THREAD

**Issue by christianimmler** [MrYsLab/s3onegpio#48]
[translations.txt](https://github.com/MrYsLab/s3onegpio/files/6087113/translations.txt)

Hi,
I added lines for the German translation of each block.

regards
@christianimmler

**Comment by MrYsLab** [comment]
Thanks for the translations. Once I have incorporated them, I will publish the new code and then close this issue. I should be able to get to this today (March 5, 2021) or tomorrow.

**Comment by MrYsLab** [comment]
I have updated the translations for Arduino, Raspberry Pi, and ESP-8266. I have also added your name to [the list of contributors.](https://mryslab.github.io/s3-extend/acks/)
Thanks again.
