### ISSUE TITLE
compare with raspbian's scratch 3 build-in extensions

### ISSUE THREAD

**Issue by gasolin** [MrYsLab/s3onegpio#6]
FYR RPi 4 + latest raspbian version provide scratch 3 build-in extensions 
https://www.raspberrypi.org/blog/scratch-3-desktop-for-raspbian-on-raspberry-pi/

![](https://www.raspberrypi.org/app/uploads/2019/08/gpio-extension.png)

maybe it worth to have a reference and have some note about the same/different approaches

![](https://github.com/MrYsLab/s3onegpio/raw/master/images/rpi_blocks.png)

**Comment by MrYsLab** [comment]
Thanks for the suggestion.

When I get some time, I will create a blog post comparing the 2 approaches.  Thanks again.
