### ISSUE TITLE
DC motor PWM control backwards 

### ISSUE THREAD

**Issue by kikituko** [MrYsLab/s3onegpio#93]
I'm using ESP8266 with Motor shield L293D with s3onegpio web serwer and scratch 3. I wonder if it is possible to set backwards rotation of the DC motor. 
I can drive two wheel car with dc motors foreward but I have no idea how to set backwards rotation.

**Comment by MrYsLab** [comment]
I am not familiar with the motor shield board, but if it uses an L293D, there are direction control pins for each of the 2 DC motors. [This article](https://lastminuteengineers.com/l293d-dc-motor-arduino-tutorial/) describes using the L293D. If you search for the "Direction Control Pins" section, you will see that you can change direction by setting the control pins. So to select a direction pin, you would use the "Write Digital Pin" block specifying the PIN you are using and whether or not you want to set that pin to a 0 or 1.

Please let me know if this answers your question.

**Comment by MrYsLab** [comment]
I am closing this issue. However, if you wish to add a comment, I will see it. If necessary, I can always reopen the issue.

**Comment by kikituko** [comment]
Thank you for sending the article. It was helpful. I couldn't set GPIO  DI 0 and 2 direction control pins  because there was no such option to  choose . In my case pins starting with 4.. Finally I have set variable and override original settings. Now it is working. Thank a lot.
