### ISSUE TITLE
Does arduino work standalone?

### ISSUE THREAD

**Issue by HaLdiMilk** [MrYsLab/s3onegpio#99]
Im curious of one thing, after making programing onto the Arduino, will i be able to use the Arduino on standalone basis? like when i disconnect the Arduino and externally power the Arduino will it behave as i coded it to via scratch?

**Comment by MrYsLab** [comment]
@HaLdiMilk The Arduino is not being programmed in the usual sense. A fixed sketch is uploaded to the Arduino that interprets commands it receives as a result of executing the Scratch blocks. With blocks like Read Sonar, the Arduino sketch will start monitoring the device and automatically send reports back to Scratch. 
So, if you disconnect the Arduino and externally power it, the fixed Server sketch will be running, but you need something to send it commands for anything to happen.

I have written a project called [Telemetrix](https://mryslab.github.io/telemetrix/) that uses a similar concept. A fixed server sketch is uploaded to the Arduino, and then a Python-based client is written to send commands to the Arduino and receive data reports for data changes.

Please let me know if this answers your question.
